export default {
    GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
    GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
    CLEAR_PRODUCT_DETAILS: "CLEAR_PRODCUT_DETAILS",
    ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
    GET_ACTIVE_CART: "GET_ACTIVE_CART",
    GET_CART_TOTALS: "GET_CART_TOTALS",
    CREATE_GUEST_ORDER: "CREATE_GUEST_ORDER",
    GET_GUEST_ORDER_DETAILS: "GET_GUEST_ORDER_DETAILS"
};


//get_cart_totals
//get acctive CLEAR_PRODCUT_DETAILS
//create guest order
//get guest order details

